#!/usr/bin/env python3
"""Reset one nearby Touchlink/ZLL device through an EFR32 coordinator.

Version: 1.0.0
Date: 2026-07-12
Generated by: GPT-5.6-terra
License: GPL-3.0-or-later

===============================================================================
USER CONFIGURATION AND PRE-FLIGHT CHECKLIST
===============================================================================

Edit/check this block before using the script:

1. DEFAULT_DEVICE
   EZSP TCP or serial endpoint of the EFR32 coordinator. Change this when your
   coordinator is not reachable at the default address.

2. DEFAULT_BAUDRATE
   Serial baud rate. It matters only for a serial endpoint, not normally for a
   TCP endpoint.

3. Command-line --channel
   Use the known Touchlink channel whenever possible, for example:
       python3 touchlink_reset.py --channel 20
   Omitting --channel scans 11..26 and resets the first responder. That is
   dangerous if more than one Touchlink device is nearby.

4. BEFORE RUNNING
   - Stop Zigbee2MQTT (or any other owner of this coordinator).
   - Verify it is really stopped; this program needs exclusive coordinator use.
   - Power the target light and place it within roughly 10 cm of the coordinator.
   - Turn off or move every other Touchlink-capable device out of range.
   - This operation is destructive: it erases the selected device's Zigbee
     network state.

5. AFTER A SUCCESSFUL RESET
   - Start Zigbee2MQTT again.
   - Enable Permit Join.
   - Power-cycle the light if it does not join immediately. Devices may expose
     a pairing signal only briefly after power is restored.

===============================================================================
WHAT THIS SCRIPT DOES
===============================================================================

Some Silicon Labs EFR32 / EmberZNet coordinators do not reliably pass normal
Touchlink scan responses to Zigbee2MQTT. This workaround enters Ember MFG
library mode and receives raw frames through `mfglibRxHandler`.

For the first matching ZLL Scan Response, it performs this time-critical,
IEEE-addressed sequence:

    Scan Request -> Scan Response -> Identify Request -> 2 seconds
    -> Reset-to-Factory-New Request

The Scan, Identify, and Reset messages reuse one random non-zero transaction
ID. The reset is unicast to the IEEE address reported in the Scan Response.

An NCP reporting a successful transmit only confirms that it accepted the
frame. Practical confirmation is a visible Identify indication followed by a
successful device reset and rejoin.

===============================================================================
PROTOCOL SETTINGS: CHANGE ONLY WITH A COMPATIBILITY REASON
===============================================================================

* SCAN_ZIGBEE_INFORMATION is 0x04 to match current zigbee-herdsman.
* IDENTIFY_TO_RESET_DELAY_SECONDS is 2.0 to match its reset flow.
* The coordinator's actual PAN ID is read before entering MFG mode and is put
  into every outgoing frame. It is logged even when it is 0x0000.
* Do not generate a different transaction ID after receiving the Scan Response;
  the target expects the one from its Scan Request.
"""

# -----------------------------------------------------------------------------
# USER-EDITABLE DEFAULTS
# -----------------------------------------------------------------------------
# Change DEFAULT_DEVICE to the EZSP TCP/serial endpoint of your coordinator.
# DEFAULT_BAUDRATE normally matters only for a serial endpoint. Prefer a known
# channel via `--channel`; scanning all channels resets the first responder.
DEFAULT_DEVICE = "tcp://192.168.1.61:6638"
DEFAULT_BAUDRATE = 115200
DEFAULT_SCAN_WAIT_SECONDS = 2.0

import argparse
import asyncio
import contextlib
import sys
from random import randint
from typing import Any

import bellows
import bellows.cli.util as util
from bellows.types import basic, named


class EzspStruct:
    """Small serializer for the fixed raw 802.15.4/NWK/APS/ZCL ZLL frames."""

    _fields: list[tuple[Any, ...]] = []

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        for index, value in enumerate(args):
            self.set(self._fields[index][0], value)
        for name, value in kwargs.items():
            self.set(name, value)
        for field in self._fields:
            if len(field) >= 3 and getattr(self, field[0], None) is None:
                self.set(field[0], field[2])

    def set(self, name: str, value: Any) -> None:
        for field in self._fields:
            if field[0] == name:
                setattr(self, name, field[1](value))
                return
        raise ValueError(f"Unknown frame field: {name}")

    def serialize(self) -> bytes:
        return b"".join(getattr(self, field[0]).serialize() for field in self._fields)

    @classmethod
    def deserialize(cls, data: bytes) -> tuple[Any, bytes]:
        result = cls()
        for field in cls._fields:
            value, data = field[1].deserialize(data)
            setattr(result, field[0], value)
        return result, data


def zll_interpan_fields(command: int, fields: list[tuple[Any, ...]], broadcast: bool = False) -> list[tuple[Any, ...]]:
    """Return the common raw legacy ZLL inter-PAN header layout."""
    destination = ("dst", basic.uint16_t, 0xFFFF) if broadcast else ("extDst", named.EmberEUI64)
    return [
        ("frameControl", basic.uint16_t, 0xC801 if broadcast else 0xCC01),
        ("seq", basic.uint8_t),
        ("dstPan", basic.uint16_t, 0xFFFF),
        destination,
        ("srcPan", basic.uint16_t),
        ("extSrc", named.EmberEUI64),
        ("networkLayerFrameControl", basic.uint16_t, 0x000B),
        ("supportLayerFrameControl", basic.uint8_t, 0x0B if broadcast else 0x03),
        ("cluster", basic.uint16_t, 0x1000),
        ("profile", basic.uint16_t, 0xC05E),
        ("clusterLibraryFrameControl", basic.uint8_t, 0x11),
        ("clusterLibrarySeq", basic.uint8_t, 0),
        ("command", basic.uint8_t, command),
    ] + fields + [("crc", basic.uint16_t, 0x116A)]


class AckFrame(EzspStruct):
    _fields = [("frameControl", basic.uint16_t, 0x0002), ("seq", basic.uint8_t)]


class ScanReq(EzspStruct):
    _fields = zll_interpan_fields(
        0,
        [("transactionId", basic.uint32_t), ("zigbeeInfo", basic.uint8_t, 0x04), ("zllInfo", basic.uint8_t, 0x12)],
        broadcast=True,
    )


class IdentifyReq(EzspStruct):
    _fields = zll_interpan_fields(0x06, [("transactionId", basic.uint32_t), ("duration", basic.uint16_t, 0xFFFF)])


class FactoryResetReq(EzspStruct):
    _fields = zll_interpan_fields(0x07, [("transactionId", basic.uint32_t)])


class ScanResp(EzspStruct):
    _fields = zll_interpan_fields(
        0x01,
        [
            ("transactionId", basic.uint32_t), ("rSSICorrection", basic.uint8_t), ("zigbeeInfo", basic.uint8_t),
            ("zllInfo", basic.uint8_t), ("keyMask", basic.uint16_t), ("responseId", basic.uint32_t),
            ("extPanId", basic.uint64_t), ("nwkUpdateId", basic.uint8_t), ("logicalChannel", basic.uint8_t),
            ("panId", basic.uint16_t), ("nwkAddr", basic.uint16_t), ("numberSubDevices", basic.uint8_t),
            ("totalGroupIds", basic.uint8_t), ("endpoint", basic.uint8_t), ("profileId", basic.uint16_t),
            ("deviceId", basic.uint16_t), ("version", basic.uint8_t), ("groupIdCount", basic.uint8_t),
        ],
    )

__version__ = "1.0.0"

# -----------------------------------------------------------------------------
# PROTOCOL COMPATIBILITY SETTINGS (normally do not edit)
# -----------------------------------------------------------------------------
IDENTIFY_TO_RESET_DELAY_SECONDS = 2.0
SCAN_ZIGBEE_INFORMATION = 0x04
SCAN_SEQUENCE = 1
IDENTIFY_SEQUENCE = 2
RESET_SEQUENCE = 3

# ZLL device IDs are classes, not manufacturer/product names. Unknown values
# stay deliberately generic so this script does not misidentify a device.
DEVICE_ID_LABELS = {
    0x0000: "ZLL on/off light (0x0000)",
    0x0100: "ZLL on/off light (0x0100)",
    0x0101: "ZLL dimmable light (0x0101)",
    0x0102: "ZLL color-dimmable light (0x0102)",
    0x0103: "ZLL extended-color light (0x0103)",
    0x0104: "ZLL color-temperature light (0x0104)",
    0x0200: "ZLL on/off light (0x0200)",
    0x0210: "ZLL color light (0x0210)",
}


def eui_text(eui: Any) -> str:
    """Format an Ember EUI64 for readable output."""
    return str(eui).strip("[]")


def model_label(device_id: int) -> str:
    """Return the advertised ZLL class without inventing a vendor/model name."""
    return DEVICE_ID_LABELS.get(device_id, f"Unknown ZLL device (0x{device_id:04X})")


async def send_packet(ezsp: Any, packet: bytes, label: str) -> None:
    """Send one raw frame and fail immediately when the NCP rejects it."""
    status = (await ezsp.sendRawMessage(packet))[0]
    if getattr(status, "name", None) != "SUCCESS" and int(status) != 0:
        raise RuntimeError(f"{label} was rejected by the NCP: {status}")


async def run(args: argparse.Namespace) -> int:
    """Run one scan/identify/reset transaction and release MFG mode on exit."""
    print(f"Connecting to {args.device} ...")
    ezsp = await util.setup(args.device, args.baudrate)
    mfg_started = False
    callback_id = None
    reset_sent = asyncio.Event()
    reset_in_progress = False
    reset_task: asyncio.Task[None] | None = None
    coordinator_eui64: Any = None

    # State belonging to the current Scan Request. A response with any other
    # transaction ID cannot trigger a reset.
    current: dict[str, int] = {"channel": 0, "transaction": 0, "pan_id": 0}

    async def identify_then_reset(response: Any) -> None:
        """Continue one valid Scan Response without manual-delay interaction."""
        transaction = current["transaction"]
        print("\nTouchlink Scan Response:")
        print(f"  IEEE address: {eui_text(response.extSrc)}")
        print(f"  Channel:      {current['channel']}")
        print(f"  ZLL device:   {model_label(int(response.deviceId))}")
        print(f"  Endpoint:     {int(response.endpoint)}")
        print(f"  Transaction:  0x{transaction:08X}")

        # IEEE-addressed inter-PAN Identify using the Scan Request transaction.
        identify = IdentifyReq(
            seq=IDENTIFY_SEQUENCE,
            srcPan=current["pan_id"],
            extSrc=coordinator_eui64,
            transactionId=transaction,
            extDst=response.extSrc,
            frameControl=0xCC21,
        ).serialize()
        await send_packet(ezsp, identify, "Touchlink Identify Request")

        # Do not replace this delay with a manual prompt. A delayed reset would
        # no longer be part of the fresh Touchlink transaction.
        await asyncio.sleep(IDENTIFY_TO_RESET_DELAY_SECONDS)

        reset = FactoryResetReq(
            seq=RESET_SEQUENCE,
            srcPan=current["pan_id"],
            extSrc=coordinator_eui64,
            transactionId=transaction,
            extDst=response.extSrc,
            frameControl=0xCC21,
        ).serialize()
        await send_packet(ezsp, reset, "Touchlink Reset-to-Factory-New Request")
        print("  Sequence:     Identify -> 2 s -> targeted reset transmitted")
        reset_sent.set()

    def receive_callback(frame_name: str, callback_data: Any) -> None:
        """Handle only the first raw Scan Response matching the active request."""
        nonlocal reset_in_progress, reset_task
        if frame_name != "mfglibRxHandler" or reset_in_progress or reset_sent.is_set():
            return
        try:
            lqi, rssi, packet = callback_data
            response, _remaining = ScanResp.deserialize(packet)
        except (ValueError, IndexError, TypeError):
            # MFG mode receives unrelated radio traffic as well.
            return

        # The frame parser is intentionally dynamic; use getattr for runtime fields.
        if int(getattr(response, "transactionId")) != current["transaction"]:
            return

        reset_in_progress = True
        print(f"  RX: RSSI {int(rssi)} dBm, LQI {int(lqi)}")

        async def acknowledge_then_continue() -> None:
            # Raw MFG receive needs an explicit MAC acknowledgement before the
            # following inter-PAN unicast commands are transmitted.
            ack = AckFrame(seq=getattr(response, "seq")).serialize()
            await send_packet(ezsp, ack, "MAC ACK for Scan Response")
            await identify_then_reset(response)

        reset_task = asyncio.create_task(acknowledge_then_continue())

    try:
        # Read these before MFG mode changes the coordinator radio state.
        eui = await ezsp.getEui64()
        coordinator_eui64 = named.EmberEUI64(*eui)
        network = await ezsp.getNetworkParameters()
        if getattr(network[0], "name", None) != "SUCCESS":
            raise RuntimeError(f"Could not read network parameters: {network[0]}")
        current["pan_id"] = int(network[2].panId)
        print(f"Coordinator EUI64: {coordinator_eui64}; PAN ID: 0x{current['pan_id']:04X}")

        # MFG mode is the EFR32 workaround for missing normal Inter-PAN RX.
        status = (await ezsp.mfglibStart(True))[0]
        if getattr(status, "name", None) != "SUCCESS" and int(status) != 0:
            raise RuntimeError(f"Could not start MFG library mode: {status}")
        mfg_started = True
        callback_id = ezsp.add_callback(receive_callback)

        channels = [args.channel] if args.channel else list(range(11, 27))
        for channel in channels:
            status = (await ezsp.mfglibSetChannel(channel))[0]
            if getattr(status, "name", None) != "SUCCESS" and int(status) != 0:
                print(f"Channel {channel}: unavailable ({status})")
                continue

            current["channel"] = channel
            # Every Scan Request must create a fresh random non-zero ID.
            current["transaction"] = randint(1, 0xFFFFFFFF)
            print(f"Scanning channel {channel} ...")
            request = ScanReq(
                seq=SCAN_SEQUENCE,
                srcPan=current["pan_id"],
                extSrc=coordinator_eui64,
                transactionId=current["transaction"],
                zigbeeInfo=SCAN_ZIGBEE_INFORMATION,
            ).serialize()
            await send_packet(ezsp, request, "Touchlink Scan Request")

            try:
                await asyncio.wait_for(reset_sent.wait(), timeout=args.wait)
                break
            except asyncio.TimeoutError:
                # A matching callback may have started just before the timeout;
                # wait for it rather than invalidate its transaction by scanning
                # another channel.
                if reset_in_progress and reset_task is not None:
                    await reset_task
                    break

        if not reset_sent.is_set():
            print("No Touchlink device found; no reset was transmitted.")
            return 2

        print("\nThe NCP transmitted the reset request. Confirm the device reset/pairing indication.")
        return 0
    finally:
        # Cleanup prevents MFG mode from leaving the coordinator radio unusable.
        if callback_id is not None:
            ezsp.remove_callback(callback_id)
        if mfg_started:
            with contextlib.suppress(Exception):
                await ezsp.mfglibEnd()
        with contextlib.suppress(Exception):
            await ezsp.disconnect()
        print("Coordinator connection closed.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Destructive, time-critical EFR32 Touchlink reset for one nearby ZLL device."
    )
    parser.add_argument("device", nargs="?", default=DEFAULT_DEVICE, help="EZSP endpoint (default: %(default)s)")
    parser.add_argument("-b", "--baudrate", type=int, default=DEFAULT_BAUDRATE, help="EZSP baud rate (default: %(default)s)")
    parser.add_argument("-c", "--channel", type=int, choices=range(11, 27), help="Known Touchlink channel (recommended)")
    parser.add_argument(
        "--wait",
        type=float,
        default=DEFAULT_SCAN_WAIT_SECONDS,
        help="Scan-response timeout per channel in seconds (default: %(default)s)",
    )
    args = parser.parse_args()
    try:
        raise SystemExit(asyncio.run(run(args)))
    except KeyboardInterrupt:
        print("\nCancelled.")
        raise SystemExit(130)
    except Exception as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
